In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

1.15.0


# Defining variables

In [2]:
a = tf.Variable(0.)
b = tf.Variable(1.)
c = tf.Variable(2.)
d = tf.Variable(3.)
print(a)

<tf.Variable 'Variable:0' shape=() dtype=float32_ref>


# Basic operations

In [3]:
ad = tf.add(c,d)
mul = tf.multiply(c,d)

ad_op = a.assign(a+b)  # a := a + b
mul_op = b.assign(b*2) # b := b*2

init = tf.global_variables_initializer() #initlasing variables


# Running a session

In [4]:
with tf.Session() as sess:
    init.run()
    for i in range(5):
        sess.run(ad_op)
        sess.run(mul_op)
        sess.run(ad)
        sess.run(mul)
        
    print(ad.eval())
    print(mul.eval())
    print(ad_op.eval())
    print(mul_op.eval())
    print(a.eval())
    print(b.eval())
    
sess.close()

5.0
6.0
63.0
64.0
63.0
64.0


In [5]:
node1 = tf.constant(5.0,dtype = tf.float64)
node2 = tf.constant(6.0,dtype = tf.float64)
node3 = tf.add(node1 , node2)
node4 = tf.multiply(node1, node2)

with tf.Session() as sess:
    sess.run(node3)
    print(node3.eval())
    sum_ = node3.eval()
print(sum_)
tf.Session().run(node4)

11.0
11.0


30.0

# Cpu and Gpu (Don't run this cell)

In [ ]:
with tf.device("/cpu:0"):
    node1 = tf.constant(5.0,dtype = tf.float32)
    node2 = tf.constant(6.0,dtype = tf.float32)
    node3 = tf.add(node1 , node2)
    su = tf.Session().run(node3)
    print(su)
with tf.device ("/gpu:0"):
    node1 = tf.constant(5.0,dtype = tf.float64)
    node2 = tf.constant(6.0,dtype = tf.float64)
    node4 = tf.multiply(node1, node2)
    print(tf.Session().run(node4))

    

# Variables and initialisation

In [23]:
node = tf.Variable(tf.zeros([3,4])) #assign it some initial value
init = tf.global_variables_initializer()
with tf.Session() as sess :
    sess.run(init)
    print(sess.run(node))
    node = node.assign(node + tf.ones([3,4]))
    print(sess.run(node))
    #print(sess)
    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Placeholders

In [36]:
np.random.seed(0)

a = tf.placeholder(tf.float32 , shape = (2,4))
b = tf.placeholder(tf.float32 , shape = (4,3))

sum_ = tf.add(a,a)
prod = tf.matmul(a,b)

with tf.Session() as sess :
    a_val = np.random.rand(a.shape[0],a.shape[1])
    b_val = np.random.rand(b.shape[0],b.shape[1])
    sum_val = sess.run(sum_ , feed_dict = {a : a_val , b : b_val})
    prod_val = sess.run(prod , feed_dict = {a : a_val , b : b_val})
    print(sum_val)
    print(prod_val)

[[1.097627  1.4303787 1.2055267 1.0897664]
 [0.8473096 1.2917882 0.8751744 1.783546 ]]
[[1.4036295 1.0932201 1.5827281]
 [1.5234628 1.2614093 1.7179563]]
